apiVersion: v1
kind: Service
metadata:
  name: flask-mongo-app-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001  # Choose a node port in the allowable range
  selector:
    app: flask-mongo-app
